title: Miles Guerin
description: '<a href="https://www.linkedin.com/in/milesguerin/" target="_blank" rel="noopener">LinkedIn</a><br>Email: milesguerin (at) gmail (dot) com'
theme: jekyll-theme-minimal
logo: /files/headshot.png
show_downloads: false
github:
  is_user_page: false
