title: Miles Guerin
description: "[Resume](/files/resume.pdf)<br>[LinkedIn](https://www.linkedin.com/in/milesguerin/)"
theme: jekyll-theme-minimal
logo: /files/headshot.png
show_downloads: false
github:
  is_user_page: false
